# Server
server.port=8080

# Database (H2 for development/offline)
spring.datasource.url=jdbc:h2:file:./data/quizzypulse;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Vaadin
vaadin.launch-browser=false
vaadin.whitelisted-packages=com.quizzypulse

# Security (Default user for testing)
spring.security.user.name=admin
spring.security.user.password=admin
